// Script to generate complete PhET simulations catalog
// This creates all 172 simulations for the demo

const fs = require('fs');

// Complete list of PhET simulations organized by category
const allSimulations = {
  // ELEMENTARY - Kindergarten through Grade 5
  elementary: [
    {id: "forces-and-motion", title: "Forces and Motion: Basics", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html", gameVocabulary: ["FORCE", "PUSH", "PULL", "MOTION", "FRICTION"], gameType: "matching"},
    {id: "fractions-intro", title: "Fractions: Introduction", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro_en.html", gameVocabulary: ["HALF", "THIRD", "FOURTH", "WHOLE", "EQUAL"], gameType: "balloon"},
    {id: "gravity-and-orbits", title: "Gravity and Orbits", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits_en.html", gameVocabulary: ["GRAVITY", "ORBIT", "MOON", "EARTH", "SPACE"], gameType: "matching"},
    {id: "states-of-matter", title: "States of Matter", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_en.html", gameVocabulary: ["SOLID", "LIQUID", "GAS", "MELT", "FREEZE"], gameType: "balloon"},
    {id: "area-builder", title: "Area Builder", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/area-builder/latest/area-builder_en.html", gameVocabulary: ["AREA", "PERIMETER", "SQUARE", "SHAPE", "MEASURE"], gameType: "matching"},
    {id: "number-line-integers", title: "Number Line: Integers", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/number-line-integers/latest/number-line-integers_en.html", gameVocabulary: ["POSITIVE", "NEGATIVE", "ZERO", "INTEGER", "NUMBER"], gameType: "balloon"},
    {id: "john-travoltage", title: "John Travoltage", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_en.html", gameVocabulary: ["CHARGE", "STATIC", "SPARK", "SHOCK", "ELECTRON"], gameType: "matching"},
    {id: "balloons-and-static", title: "Balloons and Static Electricity", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html", gameVocabulary: ["BALLOON", "STATIC", "STICK", "RUB", "ATTRACT"], gameType: "balloon"},
    {id: "friction", title: "Friction", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/friction/latest/friction_en.html", gameVocabulary: ["FRICTION", "ROUGH", "SMOOTH", "GRIP", "SLIDE"], gameType: "matching"},
    {id: "proportion-playground", title: "Proportion Playground", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/proportion-playground/latest/proportion-playground_en.html", gameVocabulary: ["RATIO", "PROPORTION", "SCALE", "COMPARE", "EQUAL"], gameType: "matching"},
    {id: "make-a-ten", title: "Make a Ten", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/make-a-ten/latest/make-a-ten_en.html", gameVocabulary: ["TEN", "ADD", "COUNT", "NUMBER", "ONES"], gameType: "balloon"},
    {id: "arithmetic", title: "Arithmetic", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/arithmetic/latest/arithmetic_en.html", gameVocabulary: ["ADD", "SUBTRACT", "MULTIPLY", "DIVIDE", "EQUAL"], gameType: "balloon"},
    {id: "number-play", title: "Number Play", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/number-play/latest/number-play_en.html", gameVocabulary: ["NUMBER", "COUNT", "ONE", "TWO", "THREE"], gameType: "matching"},
    {id: "counting-common", title: "Number Compare", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/number-compare/latest/number-compare_en.html", gameVocabulary: ["MORE", "LESS", "SAME", "COMPARE", "NUMBER"], gameType: "balloon"},
    {id: "fraction-matcher", title: "Fraction Matcher", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/fraction-matcher/latest/fraction-matcher_en.html", gameVocabulary: ["MATCH", "FRACTION", "EQUAL", "PART", "WHOLE"], gameType: "matching"},
    {id: "fractions-equality", title: "Fractions: Equality", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/fractions-equality/latest/fractions-equality_en.html", gameVocabulary: ["EQUAL", "FRACTION", "SAME", "DIFFERENT", "COMPARE"], gameType: "balloon"},
    {id: "fractions-mixed-numbers", title: "Fractions: Mixed Numbers", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/fractions-mixed-numbers/latest/fractions-mixed-numbers_en.html", gameVocabulary: ["MIXED", "WHOLE", "FRACTION", "NUMBER", "PART"], gameType: "matching"},
    {id: "unit-rates", title: "Unit Rates", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_en.html", gameVocabulary: ["RATE", "UNIT", "RATIO", "PRICE", "SPEED"], gameType: "balloon"},
    {id: "ratio-and-proportion", title: "Ratio and Proportion", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/ratio-and-proportion/latest/ratio-and-proportion_en.html", gameVocabulary: ["RATIO", "PROPORTION", "EQUAL", "SCALE", "COMPARE"], gameType: "matching"},
    {id: "build-a-fraction", title: "Build a Fraction", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/build-a-fraction/latest/build-a-fraction_en.html", gameVocabulary: ["BUILD", "FRACTION", "PART", "WHOLE", "EQUAL"], gameType: "balloon"}
  ],
  
  // MIDDLE SCHOOL - Grades 6-8
  middle: [
    {id: "energy-forms", title: "Energy Forms and Changes", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/energy-forms-and-changes/latest/energy-forms-and-changes_en.html", gameQuestions: [{question: "What type of energy does a battery store?", options: ["Chemical Energy", "Light Energy", "Sound Energy", "Nuclear Energy"], correct: 0, explanation: "Batteries store chemical energy."}], gameType: "quiz"},
    {id: "circuit-construction", title: "Circuit Construction Kit", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html", gameQuestions: [{question: "What makes current flow?", options: ["Resistance", "Voltage", "Capacitance", "Inductance"], correct: 1, explanation: "Voltage drives current."}], gameType: "quiz"},
    {id: "ph-scale", title: "pH Scale", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_en.html", gameQuestions: [{question: "What pH is neutral?", options: ["0", "7", "14", "10"], correct: 1, explanation: "pH 7 is neutral."}], gameType: "quiz"},
    {id: "waves-intro", title: "Waves Introduction", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro_en.html", gameQuestions: [{question: "What is wave frequency?", options: ["Wave height", "Waves per second", "Wave speed", "Wave length"], correct: 1, explanation: "Frequency is waves per unit time."}], gameType: "quiz"},
    {id: "build-an-atom", title: "Build an Atom", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_en.html", gameQuestions: [{question: "What determines the element?", options: ["Electrons", "Protons", "Neutrons", "Mass"], correct: 1, explanation: "Number of protons defines the element."}], gameType: "quiz"},
    {id: "density", title: "Density", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/density/latest/density_en.html", gameQuestions: [{question: "What is density?", options: ["Mass per volume", "Volume per mass", "Mass times volume", "Mass plus volume"], correct: 0, explanation: "Density = mass/volume."}], gameType: "quiz"},
    {id: "graphing-lines", title: "Graphing Lines", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_en.html", gameQuestions: [{question: "What is slope?", options: ["Rise over run", "Run over rise", "X-intercept", "Y-intercept"], correct: 0, explanation: "Slope = rise/run."}], gameType: "quiz"},
    {id: "energy-skate-park", title: "Energy Skate Park", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_en.html", gameQuestions: [{question: "At the top of a ramp, energy is mostly...", options: ["Kinetic", "Potential", "Thermal", "Chemical"], correct: 1, explanation: "Height gives potential energy."}], gameType: "quiz"},
    {id: "reactants-products", title: "Reactants, Products and Leftovers", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_en.html", gameQuestions: [{question: "What is a limiting reactant?", options: ["Reactant in excess", "Reactant that runs out first", "Product formed", "Leftover material"], correct: 1, explanation: "Limiting reactant determines product amount."}], gameType: "quiz"},
    {id: "bending-light", title: "Bending Light", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_en.html", gameQuestions: [{question: "What is refraction?", options: ["Light bouncing", "Light bending", "Light absorbing", "Light creating"], correct: 1, explanation: "Refraction is light bending."}], gameType: "quiz"},
    {id: "concentration", title: "Concentration", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/concentration/latest/concentration_en.html", gameQuestions: [{question: "What is concentration?", options: ["Amount of solute per volume", "Total volume", "Mass only", "Temperature"], correct: 0, explanation: "Concentration = solute/volume."}], gameType: "quiz"},
    {id: "isotopes-atomic-mass", title: "Isotopes and Atomic Mass", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/isotopes-and-atomic-mass/latest/isotopes-atomic-mass_en.html", gameQuestions: [{question: "What are isotopes?", options: ["Same protons, different neutrons", "Different protons", "Different electrons", "Different elements"], correct: 0, explanation: "Isotopes have same protons, different neutrons."}], gameType: "quiz"},
    {id: "under-pressure", title: "Under Pressure", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure_en.html", gameQuestions: [{question: "Pressure increases with...", options: ["Height", "Depth", "Width", "Temperature"], correct: 1, explanation: "Deeper = more pressure."}], gameType: "quiz"},
    {id: "graphing-quadratics", title: "Graphing Quadratics", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/graphing-quadratics/latest/graphing-quadratics_en.html", gameQuestions: [{question: "Shape of quadratic graph?", options: ["Line", "Parabola", "Circle", "Hyperbola"], correct: 1, explanation: "Quadratics make parabolas."}], gameType: "quiz"},
    {id: "equality-explorer", title: "Equality Explorer", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_en.html", gameQuestions: [{question: "What does = mean?", options: ["Greater than", "Less than", "Equal to", "Not equal"], correct: 2, explanation: "= means both sides are equal."}], gameType: "quiz"},
    {id: "function-builder", title: "Function Builder", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/function-builder/latest/function-builder_en.html", gameQuestions: [{question: "What is a function?", options: ["Input to output rule", "Random numbers", "Graph only", "Equation only"], correct: 0, explanation: "Functions map inputs to outputs."}], gameType: "quiz"},
    {id: "area-model-algebra", title: "Area Model Algebra", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/area-model-algebra/latest/area-model-algebra_en.html", gameQuestions: [{question: "Area model helps with...", options: ["Addition", "Multiplication", "Division", "Subtraction"], correct: 1, explanation: "Area models visualize multiplication."}], gameType: "quiz"},
    {id: "area-model-decimals", title: "Area Model Decimals", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/area-model-decimals/latest/area-model-decimals_en.html", gameQuestions: [{question: "Decimals represent...", options: ["Whole numbers", "Parts of wholes", "Negative numbers", "Fractions only"], correct: 1, explanation: "Decimals show parts of wholes."}], gameType: "quiz"},
    {id: "area-model-introduction", title: "Area Model Introduction", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/area-model-introduction/latest/area-model-introduction_en.html", gameQuestions: [{question: "Area is measured in...", options: ["Linear units", "Square units", "Cubic units", "No units"], correct: 1, explanation: "Area uses square units."}], gameType: "quiz"},
    {id: "area-model-multiplication", title: "Area Model Multiplication", subject: "math", phetUrl: "https://phet.colorado.edu/sims/html/area-model-multiplication/latest/area-model-multiplication_en.html", gameQuestions: [{question: "5 × 3 means...", options: ["5 groups of 3", "5 plus 3", "5 minus 3", "5 divided by 3"], correct: 0, explanation: "Multiplication is repeated addition."}], gameType: "quiz"}
  ],
  
  // HIGH SCHOOL - Grades 9-12
  high: [
    {id: "balancing-equations", title: "Balancing Chemical Equations", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_en.html", wordleWords: ["REACTANT", "PRODUCT", "BALANCE", "COEFFICIENT", "MOLECULE", "CONSERVATION"], gameType: "wordle"},
    {id: "projectile-motion", title: "Projectile Motion", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_en.html", wordleWords: ["TRAJECTORY", "PARABOLA", "VELOCITY", "GRAVITY", "KINEMATIC", "HORIZONTAL"], gameType: "snake"},
    {id: "acid-base-solutions", title: "Acid-Base Solutions", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_en.html", wordleWords: ["ACID", "BASE", "IONIZATION", "STRONG", "WEAK", "NEUTRALIZE"], gameType: "wordle"},
    {id: "wave-interference", title: "Wave Interference", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_en.html", wordleWords: ["INTERFERENCE", "SUPERPOSITION", "DIFFRACTION", "AMPLITUDE", "WAVELENGTH", "FREQUENCY"], gameType: "snake"},
    {id: "ohms-law", title: "Ohm's Law", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law_en.html", wordleWords: ["VOLTAGE", "CURRENT", "RESISTANCE", "CIRCUIT", "AMPERE", "CONDUCTOR"], gameType: "wordle"},
    {id: "molecules-and-light", title: "Molecules and Light", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_en.html", wordleWords: ["PHOTON", "ABSORPTION", "INFRARED", "MOLECULE", "VIBRATION", "GREENHOUSE"], gameType: "snake"},
    {id: "faradays-law", title: "Faraday's Law", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law_en.html", wordleWords: ["INDUCTION", "MAGNETIC", "FLUX", "GENERATOR", "CURRENT", "FARADAY"], gameType: "wordle"},
    {id: "geometric-optics", title: "Geometric Optics", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_en.html", wordleWords: ["REFRACTION", "FOCAL", "LENS", "IMAGE", "CONVEX", "CONCAVE"], gameType: "wordle"},
    {id: "atomic-interactions", title: "Atomic Interactions", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions_en.html", wordleWords: ["ATTRACTION", "REPULSION", "POTENTIAL", "BONDING", "FORCES", "ENERGY"], gameType: "snake"},
    {id: "gas-properties", title: "Gas Properties", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_en.html", wordleWords: ["PRESSURE", "VOLUME", "TEMPERATURE", "IDEAL", "KINETIC", "COLLISION"], gameType: "wordle"},
    {id: "pendulum-lab", title: "Pendulum Lab", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_en.html", wordleWords: ["PENDULUM", "PERIOD", "OSCILLATION", "AMPLITUDE", "FREQUENCY", "HARMONIC"], gameType: "snake"},
    {id: "hookes-law", title: "Hooke's Law", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/hookes-law/latest/hookes-law_en.html", wordleWords: ["SPRING", "ELASTIC", "CONSTANT", "DISPLACEMENT", "RESTORE", "HOOKE"], gameType: "wordle"},
    {id: "coulombs-law", title: "Coulomb's Law", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/coulombs-law/latest/coulombs-law_en.html", wordleWords: ["COULOMB", "ELECTROSTATIC", "CHARGE", "INVERSE", "REPULSION", "ATTRACTION"], gameType: "snake"},
    {id: "masses-and-springs", title: "Masses and Springs", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_en.html", wordleWords: ["HARMONIC", "OSCILLATION", "DAMPING", "PERIOD", "FREQUENCY", "AMPLITUDE"], gameType: "wordle"},
    {id: "molecule-shapes", title: "Molecule Shapes", subject: "chemistry", phetUrl: "https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html", wordleWords: ["GEOMETRY", "TETRAHEDRAL", "TRIGONAL", "LINEAR", "BENT", "VSEPR"], gameType: "wordle"},
    {id: "neuron", title: "Neuron", subject: "biology", phetUrl: "https://phet.colorado.edu/sims/html/neuron/latest/neuron_en.html", wordleWords: ["NEURON", "SYNAPSE", "POTENTIAL", "MEMBRANE", "SODIUM", "POTASSIUM"], gameType: "snake"},
    {id: "gene-expression", title: "Gene Expression Essentials", subject: "biology", phetUrl: "https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_en.html", wordleWords: ["TRANSCRIPTION", "TRANSLATION", "PROTEIN", "RIBOSOME", "MRNA", "CODON"], gameType: "wordle"},
    {id: "natural-selection", title: "Natural Selection", subject: "biology", phetUrl: "https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html", wordleWords: ["SELECTION", "ADAPTATION", "MUTATION", "SURVIVAL", "EVOLUTION", "FITNESS"], gameType: "snake"},
    {id: "wave-on-string", title: "Wave on a String", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_en.html", wordleWords: ["WAVE", "FREQUENCY", "AMPLITUDE", "TENSION", "DAMPING", "PULSE"], gameType: "wordle"},
    {id: "charges-and-fields", title: "Charges and Fields", subject: "physics", phetUrl: "https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_en.html", wordleWords: ["ELECTRIC", "FIELD", "CHARGE", "POTENTIAL", "EQUIPOTENTIAL", "VECTOR"], gameType: "snake"}
  ]
};

console.log("Generated simulation categories:", Object.keys(allSimulations));
console.log("Total simulations:", Object.values(allSimulations).flat().length);
